appName: lars-app-backend # This value was modified by the initial-setup python script

deployment:
  image:
    repository: fraserc182/lars-app-backend # This value was modified by the initial-setup python script